In [1]:
import pandas as pd


def get_area(offset_dist, *offset):

    def first_method(offset_dist, *offset):
        count = 0
        for i in range(len(offset)):
            if i == 0 or i == len(offset) - 1:
                count += offset[i]

            elif i % 2 == 1:
                count += offset[i] * 4

            elif i % 2 == 0:
                count += offset[i] * 2

        return (count * 2 * offset_dist) / 3

        
    def alternate_method(offset_dist, *offset):
        count = 0
        for i in range(len(offset[:3])):
            if i == 0:
                count += offset[i] * 5
            elif i == 1:
                count += offset[i] * 8
            elif i == 2:
                count -= offset[i]

        count = (count * 2 * offset_dist) / 12

        count2 = 0
        for i in range(1, len(offset)):
            if i == 1 or i == len(offset) - 1:
                count2 += offset[i]

            elif i % 2 == 0:
                count2 += offset[i] * 4

            elif i % 2 == 1:
                count2 += offset[i] * 2

        count2 = (count2 * 2 * offset_dist) / 3
        return count2 + count


    if len(offset) % 2 == 1:
        return first_method(offset_dist, *offset)

    return alternate_method(offset_dist, *offset)

def half_method(offset_dist,*offset):
        count = 0
        for i in range(3):
            if i == 0:
                count += offset[i] * 5
            elif i == 1:
                count += offset[i] * 8
            elif i == 2:
                count -= offset[i]

        return (count * 2 * offset_dist) / 12
    
df_offset=pd.read_excel('offset.xlsx')
df_offset

,0.0,0.5,1.0,1.5,2.0,3.0,4.0,5.0,6.0,7.0,...,13.0,14.0,15.0,16.0,17.0,18.0,18.5,19.0,19.5,20.0
0,0.00,0.00,0.00,0.25,0.80,1.73,2.96,4.23,5.50,6.51,...,7.69,7.19,6.26,4.82,3.21,1.61,1.01,0.51,0.08,0.00
1,0.00,0.00,0.02,0.51,1.10,2.33,3.80,5.16,6.38,7.27,...,8.12,7.61,6.68,5.41,3.72,2.03,1.27,0.68,0.13,0.00
2,0.00,0.00,0.34,0.86,1.41,2.96,4.65,6.00,7.19,7.95,...,8.46,8.03,7.23,5.83,4.23,2.45,1.61,0.85,0.17,0.00
3,0.00,0.25,0.68,1.27,2.11,3.97,5.58,6.77,7.69,8.20,...,8.46,8.29,7.61,6.51,4.90,3.04,2.11,1.10,0.25,0.00
4,0.00,0.42,0.93,1.61,2.37,4.14,5.92,7.31,8.12,8.37,...,8.46,8.37,7.95,7.02,5.66,3.80,2.79,1.69,0.59,0.00
5,0.00,0.59,1.27,2.03,2.87,4.65,6.34,7.61,8.29,8.46,...,8.46,8.46,8.20,7.61,6.59,5.16,4.23,3.21,2.20,1.10
6,0.17,0.85,1.69,2.45,3.38,5.24,6.76,7.86,8.37,8.46,...,8.46,8.46,8.37,8.12,7.52,6.51,5.83,4.99,4.06,3.04
7,0.42,1.27,2.20,3.13,4.14,5.83,7.19,8.03,8.37,8.46,...,8.46,8.46,8.46,8.37,8.12,7.52,7.02,6.43,5.66,4.73
8,0.85,1.94,3.04,4.06,4.99,6.59,7.69,8.20,8.46,8.46,...,8.46,8.46,8.46,8.46,8.37,8.12,7.78,7.27,6.59,5.75

In [2]:
offset_dist=float(input('enter offset dist: '))

areas={}
with pd.ExcelWriter('bonjean.xlsx') as writer:
    for i in range(len(df_offset.columns)):
        areas[f'stn{i}']=[half_method(offset_dist,*df_offset.iloc[:3,i]),
                          get_area(offset_dist,*df_offset.iloc[:3,i])]
        for j in range(4,len(df_offset)+1):  
            areas[f'stn{i}'].append(get_area(offset_dist,*df_offset.iloc[:j,i]))
            
        
            
        df=pd.DataFrame({f'0-{k}':[areas[f'stn{i}'][k-1]] for k in range(1,len(df_offset))})
        sheet_names=[f'stn{i}' for i in df_offset.columns]
        df.to_excel(writer,sheet_name=sheet_names[i],index=False)

enter offset dist: 25